apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: aicoe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: testcrumt360.azurecr.io/server_test_1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: aicoe
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer