class Constants:
    DATABASE_NAME = "NHChat"
    COSMOS_KEY_SECRET_NAME = "COSMOS_KEY"
    COSMOS_ENDPOINT_SECRET_NAME = "COSMOS_ENDPOINT"
    PARTITION_KEY_PATH = "/PK"
    OFFER_THROUGHPUT = 400
    KEY_VAULT_NAME = "nh-aicoe-kv"
